### ISSUE TITLE
Prevent player from placing blocks outside the board

### ISSUE THREAD

**Issue by seanx63** [BGH76/TetrisGenSK#8]
Currently player can use the extra canvas width to place blocks and use those blocks to clear lines.

**Comment by seanx63** [comment]
Fixed with #15

**Comment by GeorgeKurian28** [comment]
I have the bug sorted for when the block is not rotated, So I will finish it off when the block is rotated once we finish the rotation.

**Comment by seanx63** [comment]
Fixed with #19
